#!/bin/bash

source common

MERGE_MSG=""

while getopts "m:h" opt; do
    case $opt in
        m) MERGE_MSG="$OPTARG" ;;
        h)
            echo "Usage: $(basename "$0") [-m \"merge commit message\"] [source_branch] [target_branch]"
            echo "  -m message   Use this message for the merge commit (then push target branch)."
            echo "  source_branch  Branch to merge (default: current branch, or . for current)"
            echo "  target_branch  Branch to merge into (default: develop)"
            exit 0
            ;;
        \?) echo "Usage: $(basename "$0") [-m message] [source_branch] [target_branch]"; exit 1 ;;
    esac
done
shift $((OPTIND - 1))

push $MERGE_MSG
check_cmd "Failed to push code to remote"

# Get the current branch name
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Check if the source branch parameter is provided
if [ -z "$1" -o "$1" == "." ]; then
    SOURCE_BRANCH=$CURRENT_BRANCH
else
    SOURCE_BRANCH=$1
fi

# Set the target branch to 'develop' if not provided
if [ -z "$2" ]; then
    TARGET_BRANCH=develop
else
    TARGET_BRANCH=$2
fi

info "Checking out target branch"
git checkout "$TARGET_BRANCH"
check_cmd "Failed to checkout target branch"

info "Pulling latest changes from target branch"
git pull origin "$TARGET_BRANCH"
check_cmd "Failed to pull latest changes from target branch"

info "Merging code from source branch"
git merge "$SOURCE_BRANCH"
check_cmd "Failed to merge code from source branch"

info "Pushing code to remote"
git push origin "$TARGET_BRANCH"
check_cmd "Failed to push code to remote"

info "Checking out source branch"
git checkout "$SOURCE_BRANCH"
check_cmd "Failed to checkout source branch"

success "Code deployed successfully"

exit 0