#!/bin/bash

source common

# Check if the source branch parameter is provided
if [ -z "$1" ]; then
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
    BRANCH=$1
fi

git pull origin "$BRANCH" --rebase=false --no-edit
check_cmd "Failed to pull code from remote"

success "Code pulled from remote"

exit 0
