#!/bin/bash

# Function to check the status of the last command and exit if it failed
check_command_status() {
    if [ $? -ne 0 ]; then
        echo "---> ERR: $1. Exiting."
        exit 1
    fi
}


# Check if the source branch parameter is provided
if [ -z "$1" ]; then
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
    BRANCH=$1
fi


git pull origin "$BRANCH" --rebase=false --no-edit
check_command_status "Failed to pull code from remote"
