#!/bin/bash

source common

# Check if the source branch parameter is provided
if [ -z "$1" ]; then
    MSG="mirror update"
else
    MSG=$1
fi

status

sep

info "Committing changes"

git add .

git commit -m "$MSG"

info "Pushing changes to remote"
git push "${@:2}"
check_cmd "Failed to push code to remote"

success "Changes pushed to remote"

exit 0
