#!/bin/bash

source common

# Check if the source branch parameter is provided
if [ -z "$1" ]; then
    MSG="mirror update"
else
    MSG=$1
fi

status

sep

info "Pushing code to remote"

git add .

git commit -m "$MSG"

git push "${@:2}"
check_cmd "Failed to push code to remote"

success "Code pushed to remote"

exit 0
